# -*- coding: utf-8 -*-
"""lab_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W95GdJqLrpm0ui4kLFHJpUkc5adYVCQ0
"""

students = [
    "Name: Rohan Kumar, Roll: 23045, Course: CSE, Email: rohan.kumar123@bpmce.ac.in",
    "Name: Anjali Singh, Roll: 23102, Course: ECE, Email: anjali.singh@bpmce.ac.in",
    "Name: Saurabh Kumar, Roll: 23011, Course: ME, Email: saurabhk@bpmce.ac.in",
    "Name: Neha Kumari, Roll: 22999, Course: CE, Email: neha.kumari@bpmce.ac.in",
    "Name: aman raj, Roll: 23077, Course: CSE, Email: amanraj123@bpmce.ac.in"
]

for student in students:
    parts = student.split(",")
    for part in parts:
        key, value = part.split(":")
        key = key.strip()
        value = value.strip()
        if key == "Name":
            name = value
        elif key == "Roll":
            roll = value
        elif key == "Course":
            course = value
        elif key == "Email":
            email = value




    if name[0].isupper():
        name_check = "Name starts with a capital letter"
    else:
        name_check = "Name does NOT start with a capital letter"




    if roll.isdigit() and len(roll) == 5:
        roll_check = "Roll number is valid"
    else:
        roll_check = "Roll number is NOT valid"




    if "@" in email and "." in email and email.endswith("@bpmce.ac.in") and email.split("@")[0].islower():
        email_check = "Email is valid"
    else:
        email_check = "Email is NOT valid"




    print("Name:", name)
    print("Roll:", roll)
    print("Course:", course)
    print("Email:", email)
    print(name_check)
    print(roll_check)
    print(email_check)
    print("-" * 40)